import type { Metadata } from "next";
import { Inter, Ubuntu } from "next/font/google";
import "./globals.css";
import * as React from "react";

const MainFont = Ubuntu({
  subsets: ["latin-ext"],
  weight: [
    "300",
    "400",
    "700",
    "500"
  ]
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${MainFont.className} text-white`}>
        {children}
      </body>
    </html>
  );
}
